### ISSUE TITLE
Server Not Authorized. Please check your server permission.

### ISSUE THREAD

**Issue by MATTYGILO** [square/in-app-payments-server-quickstart#13]
I get this error
**{"errorMessage":"Server Not Authorized. Please check your server permission."}**
when running
`curl -X POST 'valid url'         -H 'Content-Type: application/json'         -d '{ "nonce": "valid nonce" }'

`

**Comment by StephenJosey** [comment]
If you're getting Unauthorized using this quickstart server, that means the access token you provided is incorrect. Please make sure you're grabbing either the sandbox or production access token from the Square developer dashboard and putting it in the Heroku configuration page.
