### ISSUE TITLE
Where to mention amount to be charged?

### ISSUE THREAD

**Issue by MuhammadFaizan980** [square/in-app-payments-server-quickstart#14]
Can you please tell where to mention the amount that we need to charge. Do we need to mention it somewhere along with nonce or somewhere wlese?

**Comment by StephenJosey** [comment]
The amount is hardcoded here: https://github.com/square/in-app-payments-server-quickstart/blob/master/index.js#L126

It's a parameter of the `CreatePayment` request. Please let me know if you have more questions, though.
